import {
  Type,
  StickyNote,
  CheckSquare,
  ImageIcon,
  Link,
  FileText,
  MessageCircle,
  File,
  Video,
  AudioWaveform,
  Globe,
  MapPin,
  Camera,
  Square,
  Circle,
  Triangle,
  Diamond,
  Link2,
  Palette,
  Columns,
  LayoutDashboard,
  Table,
  GitBranch,
  Kanban,
  FileCode,
  PenTool,
  Highlighter,
  Eraser,
  Lasso,
  Vote,
  Timer,
  Presentation,
  Archive,
  Zap,
  FileSpreadsheet,
  FileImage,
  FileVideo,
  FileAudio,
  FileCode2,
  FileText as FileDoc,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { DEFAULT_ITEM_WIDTH } from "./node-definitions";

export type ItemCategory =
  | "text"
  | "media"
  | "files"
  | "organize"
  | "visual"
  | "drawing"
  | "structured"
  | "collaboration"
  | "capture";

export type ItemStatus = "available" | "experimental" | "coming-soon";

export interface ItemCapabilities {
  background?: boolean;
  stroke?: boolean;
  opacity?: boolean;
  rotation?: boolean;
  richText?: boolean;
  asset?: boolean;
  connectable?: boolean;
  container?: boolean;
  children?: boolean;
  comments?: boolean;
  editableText?: boolean;
  remoteUrl?: boolean;
  embed?: boolean;
  drawing?: boolean;
  preserveAspectRatio?: boolean;
}

export interface ItemDefinition {
  type: string;
  label: string;
  icon: LucideIcon;
  category: ItemCategory;
  status: ItemStatus;
  keywords?: string[];
  defaultWidth: number;
  defaultHeight: number;
  minWidth: number;
  minHeight: number;
  maxWidth?: number;
  maxHeight?: number;
  resizeMode: "none" | "width" | "both" | "width-content";
  preserveAspectRatio?: boolean;
  editableText?: boolean;
  capabilities?: ItemCapabilities;
}

export const ITEM_REGISTRY: ItemDefinition[] = [
  // ── TEXT & NOTES ──────────────────────────────────────────────────
  {
    type: "text",
    label: "Rich Text",
    icon: Type,
    category: "text",
    status: "available",
    keywords: ["note", "document", "writing", "rich text"],
    defaultWidth: DEFAULT_ITEM_WIDTH,
    defaultHeight: 120,
    minWidth: 200,
    minHeight: 80,
    maxWidth: 520,
    resizeMode: "width-content",
    editableText: true,
    capabilities: { background: true, richText: true, rotation: true, opacity: true },
  },
  {
    type: "sticky",
    label: "Sticky Note",
    icon: StickyNote,
    category: "text",
    status: "available",
    keywords: ["note", "sticky", "post-it", "quick"],
    defaultWidth: DEFAULT_ITEM_WIDTH,
    defaultHeight: 180,
    minWidth: 180,
    minHeight: 140,
    maxWidth: 420,
    resizeMode: "both",
    capabilities: { background: true, rotation: true, opacity: true },
  },
  {
    type: "todo",
    label: "To-do",
    icon: CheckSquare,
    category: "text",
    status: "available",
    keywords: ["task", "tasks", "checklist", "check"],
    defaultWidth: DEFAULT_ITEM_WIDTH,
    defaultHeight: 160,
    minWidth: 240,
    minHeight: 120,
    maxWidth: 520,
    resizeMode: "both",
    capabilities: { background: true, rotation: true, opacity: true },
  },
  {
    type: "code",
    label: "Code Block",
    icon: FileCode2,
    category: "text",
    status: "available",
    keywords: ["code", "snippet", "programming", "developer"],
    defaultWidth: DEFAULT_ITEM_WIDTH,
    defaultHeight: 200,
    minWidth: 280,
    minHeight: 140,
    maxWidth: 800,
    resizeMode: "both",
    editableText: true,
    capabilities: { background: true, rotation: true, opacity: true, editableText: true },
  },
  {
    type: "document",
    label: "Document Card",
    icon: FileDoc,
    category: "text",
    status: "coming-soon",
    keywords: ["document", "card", "page", "link"],
    defaultWidth: DEFAULT_ITEM_WIDTH,
    defaultHeight: 140,
    minWidth: 240,
    minHeight: 100,
    maxWidth: 520,
    resizeMode: "width",
    capabilities: { background: true, asset: true, remoteUrl: true },
  },

  // ── MEDIA & WEB ──────────────────────────────────────────────────
  {
    type: "image",
    label: "Image",
    icon: ImageIcon,
    category: "media",
    status: "available",
    keywords: ["image", "photo", "picture", "img"],
    defaultWidth: DEFAULT_ITEM_WIDTH,
    defaultHeight: 220,
    minWidth: 120,
    minHeight: 120,
    maxWidth: 1200,
    maxHeight: 1200,
    resizeMode: "both",
    preserveAspectRatio: true,
    capabilities: {
      background: true,
      asset: true,
      remoteUrl: true,
      rotation: true,
      opacity: true,
      preserveAspectRatio: true,
    },
  },
  {
    type: "link",
    label: "Link",
    icon: Link,
    category: "media",
    status: "available",
    keywords: ["url", "website", "bookmark", "link"],
    defaultWidth: DEFAULT_ITEM_WIDTH,
    defaultHeight: 100,
    minWidth: 200,
    minHeight: 60,
    maxWidth: 520,
    resizeMode: "width",
    capabilities: { background: true, remoteUrl: true, rotation: true, opacity: true },
  },
  {
    type: "video",
    label: "Video",
    icon: Video,
    category: "media",
    status: "available",
    keywords: ["video", "movie", "film", "mp4", "youtube", "vimeo"],
    defaultWidth: DEFAULT_ITEM_WIDTH,
    defaultHeight: 200,
    minWidth: 280,
    minHeight: 160,
    maxWidth: 800,
    maxHeight: 600,
    resizeMode: "both",
    preserveAspectRatio: true,
    capabilities: {
      background: true,
      asset: true,
      remoteUrl: true,
      rotation: true,
      opacity: true,
      preserveAspectRatio: true,
    },
  },
  {
    type: "audio",
    label: "Audio",
    icon: AudioWaveform,
    category: "media",
    status: "available",
    keywords: ["audio", "sound", "music", "podcast", "mp3"],
    defaultWidth: DEFAULT_ITEM_WIDTH,
    defaultHeight: 100,
    minWidth: 280,
    minHeight: 80,
    maxWidth: 520,
    resizeMode: "width",
    capabilities: { background: true, asset: true, remoteUrl: true, rotation: true, opacity: true },
  },
  {
    type: "embed",
    label: "Embed",
    icon: Globe,
    category: "media",
    status: "available",
    keywords: ["embed", "iframe", "youtube", "figma", "slides"],
    defaultWidth: DEFAULT_ITEM_WIDTH,
    defaultHeight: 200,
    minWidth: 280,
    minHeight: 160,
    maxWidth: 800,
    maxHeight: 600,
    resizeMode: "both",
    capabilities: { background: true, embed: true, remoteUrl: true, rotation: true, opacity: true },
  },
  {
    type: "map",
    label: "Map",
    icon: MapPin,
    category: "media",
    status: "coming-soon",
    keywords: ["map", "location", "address", "coordinates"],
    defaultWidth: DEFAULT_ITEM_WIDTH,
    defaultHeight: 200,
    minWidth: 280,
    minHeight: 160,
    maxWidth: 800,
    maxHeight: 600,
    resizeMode: "both",
    capabilities: { background: true, remoteUrl: true, rotation: true, opacity: true },
  },
  {
    type: "webcapture",
    label: "Web Capture",
    icon: Camera,
    category: "media",
    status: "coming-soon",
    keywords: ["capture", "screenshot", "web", "page"],
    defaultWidth: DEFAULT_ITEM_WIDTH,
    defaultHeight: 200,
    minWidth: 280,
    minHeight: 160,
    maxWidth: 800,
    maxHeight: 600,
    resizeMode: "both",
    capabilities: { background: true, asset: true, rotation: true, opacity: true },
  },

  // ── FILES ────────────────────────────────────────────────────────
  {
    type: "file",
    label: "File",
    icon: File,
    category: "files",
    status: "available",
    keywords: ["file", "upload", "document", "attachment"],
    defaultWidth: DEFAULT_ITEM_WIDTH,
    defaultHeight: 80,
    minWidth: 180,
    minHeight: 60,
    maxWidth: 520,
    resizeMode: "width",
    capabilities: { background: true, asset: true, remoteUrl: true, rotation: true, opacity: true },
  },
  {
    type: "pdf",
    label: "PDF",
    icon: FileImage,
    category: "files",
    status: "available",
    keywords: ["pdf", "document", "pages", "print"],
    defaultWidth: DEFAULT_ITEM_WIDTH,
    defaultHeight: 100,
    minWidth: 200,
    minHeight: 80,
    maxWidth: 520,
    resizeMode: "width",
    capabilities: { background: true, asset: true, remoteUrl: true, rotation: true, opacity: true },
  },
  {
    type: "document_file",
    label: "Document",
    icon: FileDoc,
    category: "files",
    status: "coming-soon",
    keywords: ["doc", "docx", "word", "pages"],
    defaultWidth: DEFAULT_ITEM_WIDTH,
    defaultHeight: 100,
    minWidth: 200,
    minHeight: 80,
    maxWidth: 520,
    resizeMode: "width",
    capabilities: { background: true, asset: true, remoteUrl: true, rotation: true, opacity: true },
  },
  {
    type: "spreadsheet",
    label: "Spreadsheet",
    icon: FileSpreadsheet,
    category: "files",
    status: "coming-soon",
    keywords: ["excel", "csv", "sheets", "numbers"],
    defaultWidth: DEFAULT_ITEM_WIDTH,
    defaultHeight: 100,
    minWidth: 200,
    minHeight: 80,
    maxWidth: 520,
    resizeMode: "width",
    capabilities: { background: true, asset: true, remoteUrl: true, rotation: true, opacity: true },
  },
  {
    type: "presentation",
    label: "Presentation",
    icon: FileImage,
    category: "files",
    status: "coming-soon",
    keywords: ["ppt", "powerpoint", "slides", "keynote"],
    defaultWidth: DEFAULT_ITEM_WIDTH,
    defaultHeight: 100,
    minWidth: 200,
    minHeight: 80,
    maxWidth: 520,
    resizeMode: "width",
    capabilities: { background: true, asset: true, remoteUrl: true, rotation: true, opacity: true },
  },

  // ── ORGANIZE ─────────────────────────────────────────────────────
  {
    type: "board",
    label: "Board",
    icon: LayoutDashboard,
    category: "organize",
    status: "available",
    keywords: ["board", "sub-board", "navigate", "link"],
    defaultWidth: DEFAULT_ITEM_WIDTH,
    defaultHeight: 100,
    minWidth: 220,
    minHeight: 80,
    maxWidth: 420,
    resizeMode: "width",
    capabilities: {
      background: true,
      container: true,
      children: true,
      rotation: true,
      opacity: true,
      connectable: true,
    },
  },
  {
    type: "column",
    label: "Column",
    icon: Columns,
    category: "organize",
    status: "available",
    keywords: ["column", "list", "kanban", "organize", "container"],
    defaultWidth: 300,
    defaultHeight: 400,
    minWidth: 240,
    minHeight: 200,
    maxWidth: 600,
    maxHeight: 800,
    resizeMode: "both",
    capabilities: {
      background: true,
      container: true,
      children: true,
      rotation: false,
      opacity: true,
    },
  },
  {
    type: "frame",
    label: "Frame",
    icon: Square,
    category: "organize",
    status: "available",
    keywords: ["frame", "group", "container", "section"],
    defaultWidth: 400,
    defaultHeight: 300,
    minWidth: 200,
    minHeight: 150,
    maxWidth: 1200,
    maxHeight: 900,
    resizeMode: "both",
    capabilities: {
      background: true,
      container: true,
      children: true,
      rotation: true,
      opacity: true,
      stroke: true,
    },
  },
  {
    type: "group",
    label: "Group",
    icon: Archive,
    category: "organize",
    status: "coming-soon",
    keywords: ["group", "collection", "organize"],
    defaultWidth: DEFAULT_ITEM_WIDTH,
    defaultHeight: 140,
    minWidth: 220,
    minHeight: 100,
    maxWidth: 420,
    resizeMode: "width",
    capabilities: {
      background: true,
      container: true,
      children: true,
      rotation: true,
      opacity: true,
    },
  },

  // ── VISUAL ───────────────────────────────────────────────────────
  {
    type: "connector",
    label: "Connector",
    icon: Link2,
    category: "visual",
    status: "available",
    keywords: ["connector", "arrow", "line", "connect", "edge"],
    defaultWidth: 1,
    defaultHeight: 1,
    minWidth: 1,
    minHeight: 1,
    resizeMode: "none",
    capabilities: { stroke: true, connectable: true, opacity: true },
  },
  {
    type: "shape",
    label: "Shape",
    icon: Square,
    category: "visual",
    status: "available",
    keywords: ["shape", "rectangle", "circle", "diamond", "geometry"],
    defaultWidth: 120,
    defaultHeight: 120,
    minWidth: 60,
    minHeight: 60,
    maxWidth: 400,
    maxHeight: 400,
    resizeMode: "both",
    capabilities: { background: true, stroke: true, opacity: true, rotation: true },
  },
  {
    type: "color_swatch",
    label: "Color Swatch",
    icon: Palette,
    category: "visual",
    status: "available",
    keywords: ["color", "swatch", "palette", "hex", "design"],
    defaultWidth: 140,
    defaultHeight: 100,
    minWidth: 100,
    minHeight: 80,
    maxWidth: 280,
    maxHeight: 200,
    resizeMode: "width",
    capabilities: { background: true, opacity: true, rotation: true },
  },

  // ── DRAWING ──────────────────────────────────────────────────────
  {
    type: "pen",
    label: "Pen",
    icon: PenTool,
    category: "drawing",
    status: "coming-soon",
    keywords: ["pen", "draw", "ink", "freehand"],
    defaultWidth: 1,
    defaultHeight: 1,
    minWidth: 1,
    minHeight: 1,
    resizeMode: "none",
    capabilities: { drawing: true, stroke: true, opacity: true },
  },
  {
    type: "highlighter",
    label: "Highlighter",
    icon: Highlighter,
    category: "drawing",
    status: "coming-soon",
    keywords: ["highlight", "marker", "draw"],
    defaultWidth: 1,
    defaultHeight: 1,
    minWidth: 1,
    minHeight: 1,
    resizeMode: "none",
    capabilities: { drawing: true, stroke: true, opacity: true },
  },
  {
    type: "eraser",
    label: "Eraser",
    icon: Eraser,
    category: "drawing",
    status: "coming-soon",
    keywords: ["erase", "remove", "drawing"],
    defaultWidth: 1,
    defaultHeight: 1,
    minWidth: 1,
    minHeight: 1,
    resizeMode: "none",
    capabilities: { drawing: true, opacity: true },
  },
  {
    type: "lasso",
    label: "Lasso",
    icon: Lasso,
    category: "drawing",
    status: "coming-soon",
    keywords: ["select", "lasso", "area"],
    defaultWidth: 1,
    defaultHeight: 1,
    minWidth: 1,
    minHeight: 1,
    resizeMode: "none",
    capabilities: { drawing: true, opacity: true },
  },

  // ── STRUCTURED ───────────────────────────────────────────────────
  {
    type: "table",
    label: "Table",
    icon: Table,
    category: "structured",
    status: "available",
    keywords: ["table", "grid", "rows", "columns", "data"],
    defaultWidth: 480,
    defaultHeight: 280,
    minWidth: 320,
    minHeight: 160,
    maxWidth: 1200,
    maxHeight: 800,
    resizeMode: "both",
    capabilities: {
      background: true,
      stroke: true,
      opacity: true,
      rotation: true,
      children: true,
      editableText: true,
    },
  },
  {
    type: "mindmap",
    label: "Mind Map",
    icon: GitBranch,
    category: "structured",
    status: "coming-soon",
    keywords: ["mindmap", "mind map", "brainstorm", "tree"],
    defaultWidth: 400,
    defaultHeight: 300,
    minWidth: 300,
    minHeight: 200,
    maxWidth: 1200,
    maxHeight: 900,
    resizeMode: "both",
    capabilities: {
      background: true,
      container: true,
      children: true,
      connectable: true,
      rotation: true,
      opacity: true,
    },
  },
  {
    type: "flowchart",
    label: "Flowchart",
    icon: GitBranch,
    category: "structured",
    status: "coming-soon",
    keywords: ["flowchart", "flow", "diagram", "process"],
    defaultWidth: 400,
    defaultHeight: 300,
    minWidth: 300,
    minHeight: 200,
    maxWidth: 1200,
    maxHeight: 900,
    resizeMode: "both",
    capabilities: {
      background: true,
      container: true,
      children: true,
      connectable: true,
      rotation: true,
      opacity: true,
    },
  },
  {
    type: "kanban",
    label: "Kanban",
    icon: Kanban,
    category: "structured",
    status: "coming-soon",
    keywords: ["kanban", "board", "columns", "tasks"],
    defaultWidth: 600,
    defaultHeight: 400,
    minWidth: 400,
    minHeight: 300,
    maxWidth: 1200,
    maxHeight: 900,
    resizeMode: "both",
    capabilities: {
      background: true,
      container: true,
      children: true,
      rotation: false,
      opacity: true,
    },
  },
  {
    type: "card",
    label: "Card",
    icon: LayoutDashboard,
    category: "structured",
    status: "coming-soon",
    keywords: ["card", "wireframe", "ui", "component"],
    defaultWidth: 280,
    defaultHeight: 180,
    minWidth: 200,
    minHeight: 120,
    maxWidth: 520,
    resizeMode: "both",
    capabilities: { background: true, stroke: true, opacity: true, rotation: true },
  },
  {
    type: "wireframe",
    label: "Wireframe",
    icon: LayoutDashboard,
    category: "structured",
    status: "coming-soon",
    keywords: ["wireframe", "ui", "mockup", "design"],
    defaultWidth: 360,
    defaultHeight: 240,
    minWidth: 280,
    minHeight: 180,
    maxWidth: 800,
    maxHeight: 600,
    resizeMode: "both",
    capabilities: { background: true, stroke: true, opacity: true, rotation: true },
  },

  // ── COLLABORATION ────────────────────────────────────────────────
  {
    type: "comment",
    label: "Comment",
    icon: MessageCircle,
    category: "collaboration",
    status: "available",
    keywords: ["comment", "note", "feedback", "discussion"],
    defaultWidth: DEFAULT_ITEM_WIDTH,
    defaultHeight: 100,
    minWidth: 180,
    minHeight: 60,
    maxWidth: 420,
    resizeMode: "width",
    editableText: true,
    capabilities: {
      background: true,
      rotation: true,
      opacity: true,
      editableText: true,
      comments: true,
    },
  },
  {
    type: "voting",
    label: "Voting",
    icon: Vote,
    category: "collaboration",
    status: "coming-soon",
    keywords: ["vote", "poll", "survey", "decision"],
    defaultWidth: DEFAULT_ITEM_WIDTH,
    defaultHeight: 160,
    minWidth: 240,
    minHeight: 120,
    maxWidth: 520,
    resizeMode: "both",
    capabilities: { background: true, rotation: true, opacity: true },
  },
  {
    type: "timer",
    label: "Timer",
    icon: Timer,
    category: "collaboration",
    status: "coming-soon",
    keywords: ["timer", "countdown", "clock", "pomodoro"],
    defaultWidth: 160,
    defaultHeight: 160,
    minWidth: 140,
    minHeight: 140,
    maxWidth: 280,
    maxHeight: 280,
    resizeMode: "both",
    capabilities: { background: true, rotation: true, opacity: true },
  },
  {
    type: "presentation_mode",
    label: "Presentation",
    icon: Presentation,
    category: "collaboration",
    status: "coming-soon",
    keywords: ["present", "slideshow", "slides", "demo"],
    defaultWidth: DEFAULT_ITEM_WIDTH,
    defaultHeight: 100,
    minWidth: 240,
    minHeight: 80,
    maxWidth: 520,
    resizeMode: "width",
    capabilities: { background: true, rotation: true, opacity: true },
  },

  // ── CAPTURE ──────────────────────────────────────────────────────
  {
    type: "unsorted",
    label: "Unsorted Note",
    icon: Zap,
    category: "capture",
    status: "coming-soon",
    keywords: ["quick", "capture", "inbox", "scratch"],
    defaultWidth: DEFAULT_ITEM_WIDTH,
    defaultHeight: 120,
    minWidth: 200,
    minHeight: 80,
    maxWidth: 520,
    resizeMode: "width-content",
    capabilities: { background: true, rotation: true, opacity: true, editableText: true },
  },
  {
    type: "quick_capture",
    label: "Quick Capture",
    icon: Zap,
    category: "capture",
    status: "coming-soon",
    keywords: ["quick", "capture", "instant", "scratch"],
    defaultWidth: DEFAULT_ITEM_WIDTH,
    defaultHeight: 100,
    minWidth: 200,
    minHeight: 60,
    maxWidth: 520,
    resizeMode: "width-content",
    capabilities: { background: true, rotation: true, opacity: true, editableText: true },
  },
];

export const AVAILABLE_ITEMS = ITEM_REGISTRY.filter((i) => i.status === "available");

export const ALL_CATEGORIES: ItemCategory[] = [
  "text",
  "media",
  "files",
  "organize",
  "visual",
  "drawing",
  "structured",
  "collaboration",
  "capture",
];

export const CATEGORY_LABELS: Record<ItemCategory, string> = {
  text: "Text & Notes",
  media: "Media & Web",
  files: "Files",
  organize: "Organization",
  visual: "Visual",
  drawing: "Drawing",
  structured: "Structured",
  collaboration: "Collaboration",
  capture: "Capture",
};

export const STATUS_LABELS: Record<ItemStatus, string> = {
  available: "",
  experimental: "Experimental",
  "coming-soon": "Soon",
};

export function getItemDef(type: string): ItemDefinition | undefined {
  return ITEM_REGISTRY.find((i) => i.type === type);
}
